To avoid following error: Traceback (most recent call last):   File "manage.py", line 29, in <module>     import settings # Assumed to be in the same directory.   File "src\ecm\settings.py", line 106, in <module>     if not os.path.exist(resolvePath("logs")): AttributeError: 'module' object has no attribute 'exist'
I am using isdir instead of exist